#!/bin/bash
python dna_bopt_ensemble.py --clean True --config_file ../config_files/default_image_active_learning.txt  --output_dir ../experiments/imdbwiki/ensemble7/o  --unseen_reg maxvar --gammas 0 2 5 10 --init_train_examples 2000 --num_acks 0 --report_zero_gamma True --model_init_seed 9 --data_split_seed 9 --suffix 2k_reg2_maxvar_g00020510_3
python dna_bopt_ensemble.py --clean True --config_file ../config_files/default_image_active_learning.txt  --output_dir ../experiments/imdbwiki/ensemble7/o  --unseen_reg maxvar --gammas 0 2 5 10 --init_train_examples 2000 --num_acks 0 --report_zero_gamma True --model_init_seed 9 --data_split_seed 9 --suffix 2k_reg2_maxvar_g00020510_11
python dna_bopt_ensemble.py --clean True --config_file ../config_files/default_image_active_learning.txt  --output_dir ../experiments/imdbwiki/ensemble7/o  --unseen_reg maxvar --gammas 0 2 5 10 --init_train_examples 2000 --num_acks 0 --report_zero_gamma True --model_init_seed 9 --data_split_seed 9 --suffix 2k_reg2_maxvar_g00020510_19
python dna_bopt_ensemble.py --clean True --config_file ../config_files/default_image_active_learning.txt  --output_dir ../experiments/imdbwiki/ensemble7/o  --unseen_reg maxvar --gammas 0 2 5 10 --init_train_examples 2000 --num_acks 0 --report_zero_gamma True --model_init_seed 9 --data_split_seed 9 --suffix 2k_reg2_maxvar_g00020510_27
python dna_bopt_ensemble.py --clean True --config_file ../config_files/default_image_active_learning.txt  --output_dir ../experiments/imdbwiki/ensemble7/o  --unseen_reg maxvar --gammas 0 2 5 10 --init_train_examples 2000 --num_acks 0 --report_zero_gamma True --model_init_seed 9 --data_split_seed 9 --suffix 2k_reg2_maxvar_g00020510_35
python dna_bopt_ensemble.py --clean True --config_file ../config_files/default_image_active_learning.txt  --output_dir ../experiments/imdbwiki/ensemble7/o  --unseen_reg maxvar --gammas 0 2 5 10 --init_train_examples 2000 --num_acks 0 --report_zero_gamma True --model_init_seed 9 --data_split_seed 9 --suffix 2k_reg2_maxvar_g00020510_43
python dna_bopt_ensemble.py --clean True --config_file ../config_files/default_image_active_learning.txt  --output_dir ../experiments/imdbwiki/ensemble7/o  --unseen_reg maxvar --gammas 0 2 5 10 --init_train_examples 2000 --num_acks 0 --report_zero_gamma True --model_init_seed 9 --data_split_seed 9 --suffix 2k_reg2_maxvar_g00020510_51

